Add nicer error message for agents without tools (#146)
Adds a check for empty tools being used in agent configs. If we don't find any tools, raises an exception with the name of the llm in question to make debugging easier. Sample output:

```
aiq run --config_file workflow.yaml --input foo.msg
[...]
ValueError: No tools specified for ReAct Agent 'email_extraction_llm'
Error: No tools specified for ReAct Agent 'email_extraction_llm'
```

Closes #145

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/AgentIQ/blob/develop/docs/source/advanced/contributing.md).
- We require that all contributors "sign-off" on their commits. This certifies that the contribution is your original work, or you have rights to submit it under the same license, or a compatible license.
  - Any contribution which contains commits that are not Signed-Off will not be accepted.
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

Authors:
  - Jesse Kornblum (https://github.com/jkornblum-nv)

Approvers:
  - Yuchen Zhang (https://github.com/yczhang-nv)

URL: https://github.com/NVIDIA/AgentIQ/pull/146
Signed-off-by: Yuchen Zhang <134643420+yczhang-nv@users.noreply.github.com>